### ISSUE TITLE
Requires PHP 8.1

### ISSUE THREAD

**Issue by JeRoNZ** [concretecms-community-store/community_store_paypal_checkout#1]
vendor/composer/platform_check.php enforces PHP8.1 as a requirement. Took me a while to find that because installing on Concrete 8.5.12/PHP7.2LTS threw up a blank screen and no error message. Might be handy to add this requirement into the README.

**Comment by Mesuva** [comment]
I totally missed this, as this required the latest CS, and then I've been testing that on V9, and therefore trying to run everything on 8.1.

I'll put a note in the readme!
